---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    # We are carrying a backport into 2.14. We pin to <2.15 so we don't break
    # builds as soon as 2.15 drops. We should drop our backport and remove this pin
    # once 2.15 comes out.
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - awx.awx
      - amazon.aws
      - ansible.posix
      - ansible.windows
      - awx.awx
      - azure.azcollection
      - google.cloud
      - kubernetes.core
      - openstack.cloud
      - ovirt.ovirt
      - redhatinsights.insights
      - community.aws
      - community.general
  system: |
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    python-unversioned-command [platform:rpm]
    unzip [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    jq
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  prepend_final:
    - RUN $PYCMD -m pip install --no-cache-dir --upgrade pip
  append_final:
    # - RUN alternatives --set python /usr/bin/python3
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - COPY --from=1password/op:1.12.5 /usr/local/bin/op /usr/bin/op
    - COPY --from=hashicorp/packer:light /bin/packer /usr/sbin/packer
    # - ADD https://raw.githubusercontent.com/ansible/ansible/ff3ee9c4bdac68909bcb769091a198a7c45e6350/lib/ansible/cli/inventory.py /usr/local/lib/python3.9/site-packages/ansible/cli/inventory.py
    # - RUN chmod 0644 /usr/local/lib/python3.9/site-packages/ansible/cli/inventory.py
    - RUN mkdir -p /var/run/receptor
    - RUN $PYCMD -m pip uninstall -y ansible-core && $PYCMD -m pip install --force ansible==2.9.27
    # - ADD run.sh /run.sh
    # - CMD /run.sh
    # - USER 1000
    - RUN git lfs install --system
